### ISSUE TITLE
Build error with segfault on Travis

### ISSUE THREAD

**Issue by juliohm** [mauro3/SimpleTraits.jl#21]
Can you please confirm the build error below is caused by this package?

https://travis-ci.org/juliohm/ImageQuilting.jl/jobs/200428164

I recently added the `DOCUMENTER_KEY` to the build and it started failing somehow.

**Comment by timholy** [comment]
Also spotted [here](https://travis-ci.org/JuliaIO/ImageMagick.jl/builds/200532780), on both Linux and OSX with Julia 0.5. @juliohm, does it fail for you locally? I'm running the `release-0.5` build of Julia, and Travis is running 0.5.0---maybe that's the difference?

**Comment by juliohm** [comment]
Hi @timholy, I am using Julia 0.5.1-pre+31, the tests pass locally, I am restarting the build on Travis to see if something changes.

**Comment by timholy** [comment]
That's the same branch I'm using. Some more information here: https://github.com/JuliaLang/METADATA.jl/pull/7917#issuecomment-279152314.

**Comment by tkoolen** [comment]
I'm encountering the same problem in RigidBodyDynamics.jl (fixed by downgrading SimpleTraits to 0.1.1). It fails for me locally on OSX as well on Travis, see https://travis-ci.org/tkoolen/RigidBodyDynamics.jl/jobs/200563311.

**Comment by timholy** [comment]
It's not really SimpleTraits, it's MacroTools. You could pin MacroTools to v0.3.4. That would be rather less of a downgrade of functionality than downgrading SimpleTraits to 0.1.1.

**Comment by tkoolen** [comment]
I just figured that out as well. Thanks for the heads up!

**Comment by timholy** [comment]
Fixed: https://github.com/JuliaLang/METADATA.jl/pull/7927.

**Comment by juliohm** [comment]
Thank you Tim! You're incredible, all the best :-)

**Comment by timholy** [comment]
Wasn't me, thanks go to @tkelman.

**Comment by juliohm** [comment]
Thanks Tony!  Sorry for the confusion, I didn't read the thread , replying
from my email. I appreciate the help :-)

**Comment by mauro3** [comment]
After an exciting weekend for you guys, it's good to see that all is back to normal this Monday morning. Thanks to all!
