### ISSUE TITLE
Add a isiterable trait

### ISSUE THREAD

**Issue by davidanthoff** [mauro3/SimpleTraits.jl#23]
I'm not sure this can be done, but I have a vague idea that with all the new work about world counters etc. it might be feasible to add a trait that checks whether all the functions required for iteration are implemented for a type? I remember we discussed this somewhere before, and back then this didn't work because of the infamous problem in julia that I think is now solved with the world counting stuff.

Having an iterable trait would allow me to go to a *much* more elegant design in [Query.jl](https://github.com/davidanthoff/Query.jl).

**Comment by mauro3** [comment]
I'm not sure how the word-age stuff could help here, but I know next to nothing about it.  The new type-system might.  You could try to use `method_exists` inside a generated function, like described in https://github.com/mauro3/SimpleTraits.jl#advanced-features.

**Comment by davidanthoff** [comment]
See #25.

Next step for me is to understand inheritance of traits, so that I can define a trait ``IsIterableTable``, where I also check whether the element type of the iterator is a subtype of a specific type.

Thanks for the pointer to ``method_exists``, one of those cases where I would have hunted forever, but that made it all really simple :)

**Comment by mauro3** [comment]
Cool :-)

There is no inheritance built into SimpleTraits but you can do it by hand, again using generated functions.  See the `BeautyAndBeast` example in the README.

**Comment by mauro3** [comment]
Fixed by #25.
