### ISSUE TITLE
Build failure in Julia v0.6

### ISSUE THREAD

**Issue by juliohm** [mauro3/SimpleTraits.jl#24]
Can you please confirm this error is coming from SimpleTraits.jl?

https://travis-ci.org/juliohm/ImageQuilting.jl/jobs/201223318#L771

**Comment by mauro3** [comment]
Since that build ran, a new version was released where Tim fixed some stuff.  Can you try again?  If nothing else, the dep-warns should go.

**Comment by mauro3** [comment]
And I think the error was fixed in https://github.com/mauro3/SimpleTraits.jl/commit/81a5d17532097c66b210c3e9f5024918c1b1688d (which is also part of that release).

**Comment by juliohm** [comment]
I am rebuilding now...

**Comment by mauro3** [comment]
It still picks up that error: https://travis-ci.org/juliohm/ImageQuilting.jl/jobs/201223318#L770.  I can reproduce this locally by checking out 32079f0, but not on the currently released 0.3.0.  Not sure whether one of your dependencies pins it at 0.2.0?  Yes, here https://travis-ci.org/juliohm/ImageQuilting.jl/jobs/201223318#L273 it says it installs 0.2.0.

**Comment by juliohm** [comment]
@mauro3 the link you showed says 0.3.0, can you please confirm?

**Comment by mauro3** [comment]
I must have been hallucinating.  But now the error is also different: https://travis-ci.org/juliohm/ImageQuilting.jl/jobs/201223318#L1267 and seems unrelated to SimpleTraits.jl.

**Comment by juliohm** [comment]
Thank you @mauro3, I will close the issue and report it in Images.jl :)

**Comment by mauro3** [comment]
Thanks too & by the way, your ImageQuilting.jl package looks really cool.

**Comment by juliohm** [comment]
Thanks @mauro3 :) I hope the corresponding paper will come out soon. I am working on a completely separate package now, super excited to be doing research within the Julia ecosystem. It is really productive.
