### ISSUE TITLE
Build error on JuliaBox (v0.5.0)

### ISSUE THREAD

**Issue by jgoldfar** [mauro3/SimpleTraits.jl#26]
Trying to use https://github.com/JuliaDiffEq/ODE.jl on JuliaBox with a v0.5.0 kernel reproducibly fails due to some issue in this package; tried to hack at it but don't have the metaprogramming ability to help...
See https://gist.github.com/jgoldfar/6509376f7b42e2608fa969662ddd1fc1

**Comment by mauro3** [comment]
There is something odd with JuliaBox+Compat going on.  On a fresh JuliaBox profile (i.e. all packges wiped), I get this:
![1](https://cloud.githubusercontent.com/assets/4098145/23342573/59594ec6-fc5d-11e6-8232-b45b05ac7ce7.png)
which is the error you see.  But then if I open up a new notebook and do the same (i.e. sans wiping the package folder/cache), it works:
![2](https://cloud.githubusercontent.com/assets/4098145/23342581/6eebbf26-fc5d-11e6-83ae-a54df79da180.png)

Same works with SimpleTraits.  If you can reproduce this, would you mind filing a bug report for JuliaBox?  I'll close this but feel free to re-open, if you think my analysis is off.  Cheers!

**Comment by jgoldfar** [comment]
Thanks so much for debugging this issue; I should have figured I was doing something wrong. Apparently (though this hasn't come up for me before, it is mentioned on the settings page) you're not meant to use a notebook to do package management. So I guess it's expected behaviour.

**Comment by mauro3** [comment]
I see, good to know. (I'm a JuliaBox greenhorn.)
