### ISSUE TITLE
possible enhancement request: kwarg support?

### ISSUE THREAD

**Issue by sbromberger** [mauro3/SimpleTraits.jl#27]
This appears not to work:

```
@traitfn foo{G; IsMyTrait{G}}(g::G; mykw=false) = 99
```

it yields:
```
ERROR: Cannot parse argument: $(Expr(:parameters, :(mykw=false)))
```

am I overlooking something? If not, could kwargs support be added?

**Comment by mauro3** [comment]
> am I overlooking something?

No, I was overlooking something ;-)

**Comment by sbromberger** [comment]
Thank you! Would it be possible to tag a new version?

**Comment by mauro3** [comment]
Have you tested this with your application?  And sure, I'll tag a new version.

**Comment by sbromberger** [comment]
I haven't tested it yet but I hope to later this week.

**Comment by mauro3** [comment]
Tag: https://github.com/JuliaLang/METADATA.jl/pull/8325

Good to see that you're trying SimpleTraits in LightGraphs!

**Comment by sbromberger** [comment]
Not just *trying* SimpleTraits - we envision it to be a core requirement for our abstraction initiative (https://github.com/JuliaGraphs/LightGraphs.jl/pull/541).

**Comment by sbromberger** [comment]
(and thank you so much for the prompt responses to my startup issues!)

**Comment by mauro3** [comment]
Cool!  Just a heads up: from the end of next week, I'll be away from my computer for three weeks.  And next week I'll be fairly busy.  So the response time will suffer.  However, if you got a PR which is not too crazy to review, @timholy might find the time to merge it.
