### ISSUE TITLE
"ERROR: function ... does not accept keyword arguments"

### ISSUE THREAD

**Issue by sbromberger** [mauro3/SimpleTraits.jl#32]
```
julia> using SimpleTraits

julia> abstract AbFoo

julia> type Foo<:AbFoo
       a::Vector
       end

julia> type Bar<:AbFoo
              y::Float64
              end

julia> isfoo(x) = false
isfoo (generic function with 1 method)

julia> isfoo(::Type{Foo}) = true
isfoo (generic function with 2 methods)

julia> @traitdef IsFoo{X<:AbFoo}

julia> @traitimpl IsFoo{X} <- isfoo(X)

julia> @traitfn dofoo{X<:AbFoo; IsFoo{X}}(x::X, y = 3, d = 1, b = 4) = x.a[b - (y*d)]  # first element
dofoo (generic function with 8 methods)

julia> f = Foo([1,2,3,4,5])
Foo([1,2,3,4,5])

julia> dofoo(f)
ERROR: function dofoo does not accept keyword arguments
 in kwfunc(::Any) at ./boot.jl:236
 in dofoo(::Foo) at /Users/bromberger1/.julia/v0.5/SimpleTraits/src/SimpleTraits.jl:317
```

**Comment by sbromberger** [comment]
Separated from issue 2, #30 for clarity.

**Comment by ChrisRackauckas** [comment]
Could you macroexpand:

```julia
 @traitfn dofoo{X<:AbFoo; IsFoo{X}}(x::X, y = 3, d = 1, b = 4) = x.a[b - (y*d)]  # first element
```

?

**Comment by sbromberger** [comment]
```
julia> macroexpand(:@traitfn dofoo{X<:AbFoo; IsFoo{X}}(x::X, y = 3, d = 1, b = 4) = x.a[b - (y*d)])  # first element
:(dofoo{X <: AbFoo}(::Type{IsFoo{X}},x::X,y=3,d=1,b=4; ) = begin  # /Users/bromberger1/.julia/v0.5/SimpleTraits/src/SimpleTraits.jl, line 309:
            begin
                # meta: location REPL[11] dofoo 1
                ##271 = begin  # REPL[11], line 1:
                        x.a[b - y * d]
                    end
                # meta: pop location
                ##271
            end
        end)
```

**Comment by ChrisRackauckas** [comment]
Can you add `@show ex` above here:

https://github.com/mauro3/SimpleTraits.jl/blob/master/src/SimpleTraits.jl#L340

then re-run this? I need to see what trait dispatch function it's making.

**Comment by sbromberger** [comment]
```
ex = quote  # /Users/bromberger1/.julia/v0.5/SimpleTraits/src/SimpleTraits.jl, line 317:
    dofoo{X <: AbFoo}(x::X,y=3,d=1,b=4) = begin  # /Users/bromberger1/.julia/v0.5/SimpleTraits/src/SimpleTraits.jl, line 317:
            begin
                Base.@_inline_meta
                dofoo(SimpleTraits.trait(IsFoo{X}),x,y=3,d=1,b=4)
            end
        end # /Users/bromberger1/.julia/v0.5/SimpleTraits/src/SimpleTraits.jl, line 321:
    dofoo{X <: AbFoo}(::Type{IsFoo{X}},x::X,y=3,d=1,b=4; ) = begin  # /Users/bromberger1/.julia/v0.5/SimpleTraits/src/SimpleTraits.jl, line 309:
            begin
                # meta: location REPL[10] dofoo 1
                ##270 = begin  # REPL[10], line 1:
                        x.a[b - y * d]
                    end
                # meta: pop location
                ##270
            end
        end
end
```

**Comment by mauro3** [comment]
Yes, this did not work before either.  But I don't think I will have time to implement this for the next four weeks (but I plan to support this feature).  The work-around is to define them by hand.

**Comment by sbromberger** [comment]
> The work-around is to define them by hand.

I don't know how to do this, and it's blocking the new version of LightGraphs (as many functions have default assignments), so we may have to move away from traits for the moment.

**Comment by mauro3** [comment]
`f(x,y=3) = x+y` gets translated by Julia into:
```
f(x) = f(x,3)
f(x,y) = x+y
```
Thus it tells you `2 methods`:
```
julia> f(x,y=3) = x+y
f (generic function with 2 methods)
```

So instead of `@traitfn f(x::::Tr, y=3) = x+y` do:
```
@tratifn f(x::::Tr) = f(x,3)
@traitfn f(x::::Tr,y) = x+y
```

Note, that I don't think I would support a trait annotation on the default-value arguments, i.e. no `@traitfn f(x, y::::Tr=3)`.  Or would you have a use case for that?

Anyway, one of my big junks of work just vaporized, so I might find some time in the next few days after all.  I'll keep you posted.

**Comment by sbromberger** [comment]
@mauro3 thanks for the explanation. Does that mean that the number of functions for three assignments `f(x, a=1, b=2, c=3) = x + a + b + c` is as follows?
```
f(x) = f(x, 1, 2, 3)
f(x, a) = f(x, a, 2, 3)
f(x, a, b) = f(x, a, b, 3)
f(x, a, b, c) = x + a + b + c
```

If you could fix this so I don't have to "unroll" these functions that would be fantastic. There are too many right now to make this an appealing proposition but I understand your time pressures before you head out.

**Comment by mauro3** [comment]
Yep that's it.

Any thoughts on:
> Note, that I don't think I would support a trait annotation on the default-value arguments, i.e. no @traitfn f(x, y::::Tr=3). Or would you have a use case for that?

**Comment by ChrisRackauckas** [comment]
I think the fix is related to something I've seen before. `a=1, b=2, c=3` parse as `:KW` on the head, instead of as default args, when using a macro on a quoted expression sometimes. I am not sure why. You should loop through and fix the head? I remember something like that before.

**Comment by sbromberger** [comment]
> Any thoughts on:

> > Note, that I don't think I would support a trait annotation on the default-value arguments, i.e. no @traitfn f(x, y::::Tr=3). Or would you have a use case for that?

No use case anticipated for that.

**Comment by sbromberger** [comment]
also, @mauro3 - I will be able to test in near-real-time if you want to try different approaches to the "fix".

**Comment by mauro3** [comment]
@sbromberger can you give this a spin? Check the readme: https://github.com/mauro3/SimpleTraits.jl#vararg-default-argument-and-keyword-argument-trait-functions

**Comment by sbromberger** [comment]
On it. give me a few minutes.

**Comment by sbromberger** [comment]
What if I don't have a negated function?

**Comment by sbromberger** [comment]
@mauro3 this looks like it passes all my test cases. THANK YOU!!! ❤️

**Comment by sbromberger** [comment]
wait - spoke too soon. One sec.

**Comment by sbromberger** [comment]
We're all good. Please tag this!

**Comment by mauro3** [comment]
Cool 😄

**Comment by sbromberger** [comment]
@mauro3 is it possible to tag a new version before you leave? :)

**Comment by sbromberger** [comment]
ROCKING: https://github.com/JuliaLang/METADATA.jl/pull/8379

Thanks, @mauro3 !!!

**Comment by mauro3** [comment]
You're welcome.  I hope this works well for LightGraphs!  
(I'll be around for another week but with less and less time)

**Comment by sbromberger** [comment]
Understood, and I'm very grateful for your quick fixes to this. I have big plans for traits :)
