### ISSUE TITLE
What is the preferred syntax for `@traitfn`s in 0.6? (Also other style questions)

### ISSUE THREAD

**Issue by sbromberger** [mauro3/SimpleTraits.jl#35]
Right now, in 0.5, `@traitfn foo{G<:AbstractGraph; IsDirected{G}}(g::G)` is one of the options for syntax.

In 0.6, how would one rewrite this with `where`?

Additional questions: I'd really like to use Traitor syntax, but I'm unsure how to do it given my `<: AbstractGraph` parameterization. 

1) Is this parameterization a good idea? My `@traitdef` / `@traitimpl` is as follows:
```
@traitdef IsDirected{AbstractGraph}
@traitimpl IsDirected{G} <- is_directed(G)
```
2) What relationship does the `AbstractGraph` in the `@traitdef` have with the `<:AbstractGraph` in the `@traitfn`? Is one of these redundant?

**Comment by mauro3** [comment]
`where` is not supported yet.  But as the old-style is not deprecated yet, we got all of 0.6 to ponder it.

Do you mean you defined:
```
@traitdef IsDirected{G<:AbstractGraph} # here the subtypeing is missing in your example
@traitimpl IsDirected{G} <- is_directed(G)
```
Note, I've never used this subtyping in the trait-def.  You can certainly do it, but is it necessary?  Maybe someone of your users has a type hierarchy such that she'd rather not subtype AbstractGraph, but now hast to.  I think there is not much to be gained by this restraint.

Anyway, it should just work with Traitor style:
```
@traitfn f(x::::IsDirected) = 1
```

**Comment by sbromberger** [comment]
> Do you mean you defined:

yes. That's what I've got now. I thought I was being clever by limiting the trait definition to my package.

> You can certainly do it, but is it necessary?

I wanted to limit this trait to my package so that it couldn't "bleed over" into others. Perhaps this isn't a good idea?

**Comment by mauro3** [comment]
You mean if someone else defines a `IsDirected` type (or trait)?  I think, the same applies as always: if they are the "same" then make a `*Base` package for both to work with; if they are different then make them different and just fully qualify them.  I don't think the subtyping would help with that though.

**Comment by sbromberger** [comment]
In `@traitdef IsNice{X}`, what significance does the `X` have?

**Comment by mauro3** [comment]
It means that the trait takes one parameter (which is the norm).  But they can have any number, there is one example in the README.

**Comment by sbromberger** [comment]
So the name `X` doesn't carry over to anything else?

**Comment by mauro3** [comment]
Yep. (Just like for types, at least the "free" parameters.)

**Comment by sbromberger** [comment]
Perfect. Thank you.

**Comment by mauro3** [comment]
You're welcome.
