### ISSUE TITLE
request: multiple traitor-style args

### ISSUE THREAD

**Issue by sbromberger** [mauro3/SimpleTraits.jl#36]
```
julia> @traitdef IsFoo{X}

julia> abstract type AbFoo end

julia> struct Foo{T<:Number}<:AbFoo
       x::T
       end

julia> @traitimpl IsFoo{Foo}

julia> f(x::::IsFoo, y::::IsFoo) = 5
ERROR: syntax: invalid "::" syntax

julia> b(x::::IsFoo) = 6
ERROR: syntax: invalid "::" syntax

julia> @traitfn f(x::::IsFoo, y::::IsFoo) = 5
ERROR: syntax: invalid "::" syntax

julia> @traitfn b(x::::IsFoo) = 6
b (generic function with 2 methods)
```

**Comment by mauro3** [comment]
I think, I'd give this a miss with the current features of SimpleTraits.
First, this works fine:
```julia
@traitfn f{X; IsFoo{X}}(x::X,y::X) = 5
```
importantly, `x` and `y` need to have the same type. 

Thus translating this into traitor syntax:
```julia
@traitfn f{X}(x::X::IsFoo, y::X::IsFoo) = 5
```
at which point the first syntax is actually shorter.  Auto-inserting the `X` would be too magical.

**Comment by sbromberger** [comment]
Oh, wow. Is `@traitfn f{X}(x::X::IsFoo, y::X::IsFoo) = 5` valid Traitor syntax?

I agree with your assessment, btw. Thanks. Closing out.

**Comment by mauro3** [comment]
Sorry, no this is not valid traitor syntax, I now added "would give" above.  So you need to use the first syntax.
