### ISSUE TITLE
Tag a new release

### ISSUE THREAD

**Issue by davidanthoff** [mauro3/SimpleTraits.jl#37]
Would be great if you could tag a release that includes e3264 (i.e. current ``master``). That is the last thing I need before I can register and release https://github.com/davidanthoff/IterableTables.jl.

**Comment by davidanthoff** [comment]
@mauro3 Bump, any chance you could tag a release soon? Thanks.

**Comment by davidanthoff** [comment]
I actually decided to not use SimpleTraits for now, so no need to tag something for me :)

**Comment by mauro3** [comment]
Sorry about the delay! Is there any other reason you dropped SimpleTraits but the delay?

Should I still tag SimpleTraits?

**Comment by davidanthoff** [comment]
I thought for a while that I could use this and always end up with static dispatch. But with the clarification about generated functions for 0.6 that won't work. If I do end up with dynamic dispatch in any case it seems simpler right now to not use this package, mainly because I'll have to convince a large number of other packages to buy into things with IterableTables.jl, and so keeping things simple is probably more important.

**Comment by mauro3** [comment]
That makes sense, thanks for the feedback! Hopefully the `method_exists` fix Jameson mentioned will work and come soon, then the static dispatch should be back for `IsIterator`.
