### ISSUE TITLE
Possible to fix deprecation warnings in nightly?

### ISSUE THREAD

**Issue by sbromberger** [mauro3/SimpleTraits.jl#44]
Nightly now throws deprecation warnings for syntax that doesn't use the new `foo(a::T) where T` syntax for type parameterization. Is there a solution to this in SimpleTraits yet?

**Comment by mauro3** [comment]
Looks like the tests are failing too:
https://travis-ci.org/mauro3/SimpleTraits.jl/jobs/263016508

Well, I haven't moved to 0.7 yet, so this is not a priority for me.  But I'll see what I can do.  PR welcome.

**Comment by mauro3** [comment]
Currently the master is running again on Julia 0.7, however the deprecations for parameteric methods remain until #46 is fixed.

**Comment by mauro3** [comment]
See #57
