### ISSUE TITLE
Using in a package

### ISSUE THREAD

**Issue by gragusa** [mauro3/SimpleTraits.jl#50]
@mauro3 I would like to use `SimpleTraits.jl` in a package to build a generic interface. The idea is that other packages would add their types to the trait that I define in my package. I have two questions in this regard:

1. Will the master be released soon? I saw there is a divergence between master and the last release and my understanding is that the released version does not work on 0.7.

2. Assuming 1. is not a problem, is my plan sound? Would it make sense to do this or third-party packages will run into problems in adding their types to a trait defined in my package? (I guess not, but before venturing into a big refactoring I want to be sure.)

**Comment by mauro3** [comment]
Cool, thanks for considering SimpleTraits!

> 1. Will the master be released soon? I saw there is a divergence between master and the last release and my understanding is that the released version does not work on 0.7.

I can tag a release for 0.7 if you want but 0.7 is moving target.  So I'd rather you'd follow master for now, that keeps the burden lower for the good folks merging all the METADATA.jl PRs.  Once 0.7 gets a feature freeze, then I'm planning to tag a version.

Note thought, that there is the still pending transition to `where`-function syntax, which will happen sometime soonish (but next year).  Until then you have to live with deprecation warnings.  Also, if you plan to write hundreds of `@traitfn` then this transition might be a hassle.

> Assuming 1. is not a problem, is my plan sound? Would it make sense to do this or third-party packages will run into problems in adding their types to a trait defined in my package? (I guess not, but before venturing into a big refactoring I want to be sure.)

Yes, I think the grand plan is sound.  This is what SimpleTraits aims to facilitate.

**Comment by mauro3** [comment]
I think things are fixed here. In particular with #46 done.  Re-open if you feel this is not the case.
