### ISSUE TITLE
Fix 0.7 deprecations

### ISSUE THREAD

**Issue by mauro3** [mauro3/SimpleTraits.jl#57]

**Comment by sbromberger** [comment]
As of today's -nightly, the deprecations are now errors for https://github.com/mauro3/SimpleTraits.jl/blob/b38ca92027c611ea4c5ffff8463cffc5e949fc4b/src/SimpleTraits.jl#L477-L480

**Comment by sbromberger** [comment]
(is there a quick workaround for this? We're trying to keep up with 0.7/1.0 in LightGraphs.)

**Comment by mauro3** [comment]
I'm working on this and will hopefully push a fix and tag within the hour
