### ISSUE TITLE
IsIterator trait that is false for scalar numbers (IsCollection)

### ISSUE THREAD

**Issue by jtravs** [mauro3/SimpleTraits.jl#66]
I'd like to be able to dispatch on if a function is passed an iterator (such as an `Array` or `Tuple` or other collection) but not if it is an iterable scalar (such as a `Float`). See my post on discourse:

https://discourse.julialang.org/t/how-to-dispatch-on-an-iterable-e-g-accept-both-tuple-or-array/37629/3?u=jtravs

Is that possible? Something like an `IsCollection`?

**Comment by mauro3** [comment]
You can dispatch on types and traits:
```julia
julia> @traitfn g(x::T) where {T<:Number; IsIterator{T}} = "iterable and Number"
g (generic function with 2 methods)

julia> @traitfn g(x::T) where {T; IsIterator{T}} = "iterable and not Number"
g (generic function with 4 methods)

julia> @traitfn g(x::T) where {T<:Number; !IsIterator{T}} = "not iterable and Number (nothing is going to dispatch to here)"
g (generic function with 5 methods)

julia> @traitfn g(x::T) where {T; !IsIterator{T}} = "not iterable and not Number"
g (generic function with 6 methods)

julia> g(1)
"iterable and Number"

julia> g([1])
"iterable and not Number"

julia> g(nothing)
"not iterable and not Number"
```
I think that should give you what you need.

Note: the IsIterator trait uses a generated function which is not pure. Thus anything, including bad stuff, can happen.  I really should remove that generated function and make it use runtime dispatch instead.  See https://github.com/mauro3/SimpleTraits.jl/issues/40#issuecomment-564722299.

**Comment by jtravs** [comment]
Excellent, thank you!

**Comment by mauro3** [comment]
Cool.  Please do note the caveat about the generated-function and coming dynamic dispatch!

**Comment by mauro3** [comment]
Aright, here it is: https://github.com/mauro3/SimpleTraits.jl/pull/67
