### ISSUE TITLE
Method locations for `@traitfn` expansions

### ISSUE THREAD

**Issue by Keno** [mauro3/SimpleTraits.jl#72]
E.g. in 
```
ERROR: MethodError: no method matching connected_components(::TodoGraph, ::LightGraphs.Connectivity.Tarjan)
Closest candidates are:
  connected_components(::var"##295") where var"##295" at /home/keno/.julia/packages/SimpleTraits/pDUSq/src/SimpleTraits.jl:338
  connected_components(::Type{SimpleTraits.Not{IsDirected{var"##295"}}}, ::var"##295") where var"##295" at /home/keno/.julia/packages/SimpleTraits/pDUSq/src/SimpleTraits.jl:331
  connected_components(::Type{IsDirected{var"##297"}}, ::var"##297") where var"##297" at /home/keno/.julia/packages/SimpleTraits/pDUSq/src/SimpleTraits.jl:331
  ...
```
Which is from LightGraphs (which uses SimpleTraits), the methods show up as being defined in SimpleTraits, rather than LightGraphs. This is because the `@traitfn` macro introduces extra line number nodes, rather than using the line information at the expansion side. This makes finding the right method to debug quite difficult if it happens to be a `@traitfn`.

**Comment by mauro3** [comment]
x-ref: https://github.com/mauro3/SimpleTraits.jl/pull/6
