### ISSUE TITLE
Register and tag

### ISSUE THREAD

**Issue by timholy** [mauro3/SimpleTraits.jl#8]
I expect to get closer to releasing the new Images over the course of this coming week, so I'll need this package registered & tagged soon. (Or find an alternative, if you don't want to do that.)

**Comment by mauro3** [comment]
Cool, I'll register it.

**Comment by mauro3** [comment]
I'm in the progress of cleaning up the docs and came across an old docstring where I suggest the convention to have trait-names contain verbs to distinguish them from types (which usually are nouns).  I think that would lead to mostly `Is...` and `Has...` traits, e.g. `IsImmutable`.

As you're one of the few people who actually used traits: Do you think that would be useful?  Or just annoying?

**Comment by mauro3** [comment]
I'm ready to publish but I ran into https://github.com/JuliaLang/julia/issues/18455.  So, I'll wait for a day or two to hear whether I need to do debugging for that issue.

**Comment by mauro3** [comment]
PR submitted: https://github.com/JuliaLang/METADATA.jl/pull/6333

**Comment by timholy** [comment]
Awesome!

Since this package only support "boolean" traits, I think the `Is/Has` tradition is a good one. (For trait system that supported an arbitrary number of categories, e.g., `(Strided, Dense, Sparse, Computed) <: AbstractStorage`, then the `Is/Has` tradition would be less relevant.

**Comment by mauro3** [comment]
One could still go with `IsStrided`, `IsDense`, etc. no?  Although I can't fit the super trait `AbstractStorage` into the verb-first scheme.  

I'll add the style recommendation to the readme.  Once a few hundred packages have adapted SimpleTraits, I can do a rigorous evaluation ;-)

**Comment by timholy** [comment]
`IsStrided` sounds like it should have a yes/no answer and that you should be able to combine it freely with `IsDense`, whereas I meant those as exclusive possibilities. When I order 1 scoop of ice cream, I get Chocolate, Vanilla, or Strawberry, not IsChocolate, IsVanilla, or IsStrawberry.

**Comment by timholy** [comment]
Thanks!
