### ISSUE TITLE
Error when explicitly importing macros

### ISSUE THREAD

**Issue by ColdTeapot273K** [mauro3/SimpleTraits.jl#80]
### Versions

**module version**: 0.9.4
**Julia version**: 1.7
**Operating system**: Fedora 35

### Describe the bug
Non-obvious error if certain macros from `SimleTraits` were imported explicitly

### Steps/code to reproduce

Produces error:
```julia
julia> using SimpleTraits: @traitdef, @traitimpl, @traitfn

julia> @traitdef IsInteger{T}

julia> @traitimpl IsInteger{Integer}

julia> @traitfn discover_trait(x::::IsInteger) = "I'm integer!"
discover_trait (generic function with 2 methods)

julia> @traitfn discover_trait(x::::(!IsInteger)) = "I'm not integer."
ERROR: UndefVarError: SimpleTraits not defined
Stacktrace:
 [1] top-level scope
   @ REPL[6]:1
```

Works fine:
```julia
julia> using SimpleTraits

julia> @traitdef IsInteger{T}

julia> @traitimpl IsInteger{Integer}

julia> @traitfn discover_trait(x::::IsInteger) = "I'm integer!"
discover_trait (generic function with 2 methods)

julia> @traitfn discover_trait(x::::(!IsInteger)) = "I'm not integer."
discover_trait (generic function with 3 methods)
```

### Proposed solutions:

1. Allow explicit importing of macros even if it's not in the design
2. Or make a descriptive error message for such a case

**Comment by mauro3** [comment]
Note that this also errors:
```
julia> using SimpleTraits: @traitdef, @traitimpl, @traitfn

julia> @traitdef IsInteger{T}

julia> @traitimpl IsInteger{Integer}

julia> @traitfn discover_trait(x::::IsInteger) = "I'm integer!"
discover_trait (generic function with 2 methods)

julia> discover_trait(1)
ERROR: UndefVarError: SimpleTraits not defined
Stacktrace:
 [1] discover_trait(x::Int64)
   @ Main ~/julia/dot-julia-dev/SimpleTraits/src/SimpleTraits.jl:331
 [2] top-level scope
   @ REPL[5]:1
```

However, I think that the error is pretty clear and it should also be clear what to do, namely:
```
using SimpleTraits: SimpleTraits, @traitdef, @traitimpl, @traitfn
```

This package is certainly not targeted to newbies who wouldn't understand that error.

**Comment by mauro3** [comment]
Sorry!  You're right that was not politely formulated!  Bad style from me, sorry!

The `using ModuleName: ModuleName` is somewhat idiomatic with the folks careful about namespaces.  But not sure how well documented it is though.  But it's true, I did learn it not too long ago, probably reading the Julia discourse-forums.
