### ISSUE TITLE
Parametric types with traits

### ISSUE THREAD

**Issue by gdalle** [mauro3/SimpleTraits.jl#81]
Is it possible to define parametric types with `SimpleTraits.jl`?
The package documentation shows examples like
```julia
@traitfn f(x::X) where {X; IsNice{X}} = "Very nice!"
@traitfn f(x::X) where {X; !IsNice{X}} = "Not so nice!"
```
but I have yet to see the same for parametric types. What I'm looking for is something like
```julia
@traitstruct MyType{X} where {X; IsNice{X}} end
```
Does this syntax exist somewhere?

**Comment by mauro3** [comment]
No, SimpleTraits has no such feature.  I think you should be able to hand code it.  I think what you are after is called an "associated type" at least in the Rust community.  I did some work on that back in the Traits.jl days, maybe looking through that repo could be of help https://github.com/mauro3/Traits.jl.

I will close this as I do not plan to implement such a feature.  Feel free to ask more question here though.
