### ISSUE TITLE
Callable struct with trait doesn't work

### ISSUE THREAD

**Issue by gdalle** [mauro3/SimpleTraits.jl#82]
Hi there!
I would like to make all the `struct`s that satisfy a certain trait callable. Why does the following code not work?
```julia
julia> using SimpleTraits

julia> @traitdef IsVeryNice{X}

julia> @traitfn (x::X)() where {X; IsVeryNice{X}} = println("I'm so nice!")
ERROR: LoadError: function type in method definition is not a type
Stacktrace:
 [1] top-level scope
   @ ~/.julia/packages/SimpleTraits/l1ZsK/src/SimpleTraits.jl:331
```
Am I asking too much ^^?

**Comment by mauro3** [comment]
You're missing a function name (anonymous functions are not supported) and you had to many ().  Try:
```julia
@traitfn f(x::X) where {X; IsVeryNice{X}} = println("I'm so nice!")
```

I'll close this.  But you can keep asking questions here.

**Comment by gdalle** [comment]
Hi @mauro3, thanks for your answer. Actually, I don't think I was missing a function name, because I wanted to make the object `x` itself callable (see [this section](https://docs.julialang.org/en/v1/manual/methods/#Function-like-objects) in the manual). Or more precisely, I wanted to make all objects whose type `X` satisfy the trait `IsVeryNice` callable with the same method.

**Comment by mauro3** [comment]
No, that is not possible with SimpleTraits.  I am not sure that is even possible when hand coding Holy-traits.

**Comment by gdalle** [comment]
Okay thanks!

**Comment by kunzaatko** [comment]
I think that a possible workaround can be done using a function name and a generic implementation. From a project I am working on:
```julia
using SimpleTraits
@traitdef IsRadiallySymmetric{X<:TransferFunction{3}}
@traitfn function evalTF(tf::T, r, z=0) where {T <: TransferFunction; IsRadiallySymmetric{T}}
    return evalTF(tf, r, 0, z)
end
(tf::TransferFunction)(args...) = evalTF(tf, args...)
```
